tum_kullanicilar = None
tum_hisseler = None
basarili_hisseler  = None
veri_hatalari = None
veri_durumlari = None
# Gecerli_Name = None
# Gecerli_Mail = None
# Gecerli_Telegram_ID = None
# Gecerli_Aktiflik = None